spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://example.okta.com/oauth2/example
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    enabled: true
    contexts: none
